# Gradle Daemon settings
# Increased heap size to fix OutOfMemoryError during dexing
org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8

# Android properties
android.useAndroidX=true
# Enable Jetifier if using legacy libraries
android.enableJetifier=true

# Kotlin settings
kotlin.code.style=official
